language:
 - cpp

compiler:
 - gcc

os:
 - linux

install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq flex build-essential lcov
 - wget http://mirrors.kernel.org/ubuntu/pool/main/b/bison/bison_3.0.4.dfsg-1_amd64.deb
 - wget http://ftp.us.debian.org/debian/pool/main/b/bison/libbison-dev_3.0.4.dfsg-1_amd64.deb
 - sudo dpkg -i libbison-dev_3.0.4.dfsg-1_amd64.deb
 - sudo dpkg -i bison_3.0.4.dfsg-1_amd64.deb
 - sudo pip install cpp-coveralls

before_script:
 - make setup

script:
 - make debug
 - make coverage

after_success:
 - echo "Success"

after_failure:
 - echo "Failure"

after_script:
 - echo "Script Finished."

