var veridocModuleHierarchy = {"listType":"module-hierarchy","listTitle":"Module Hierarchy","listNotes":"This is the module hierarchy for the project.","listData":[{"id":"sparc_exu","children":[{"id":"bw_r_irf","children":[]}
,{"id":"sparc_exu_byp","children":[{"id":"clken_buf","children":[]}
,{"id":"dp_mux2es","children":[]}
,{"id":"dff_s","children":[]}
,{"id":"mux4ds","children":[]}
,{"id":"mux3ds","children":[]}
,{"id":"dp_buffer","children":[]}
,{"id":"sparc_exu_byp_eccgen","children":[{"id":"dff_s","children":[]}
]}
]}
,{"id":"sparc_exu_ecc","children":[{"id":"dff_s","children":[]}
,{"id":"zzecc_exu_chkecc2","children":[]}
,{"id":"mux3ds","children":[]}
,{"id":"sparc_exu_ecc_dec","children":[]}
]}
,{"id":"sparc_exu_ecl","children":[{"id":"dffrl_async","children":[]}
,{"id":"dff_s","children":[]}
,{"id":"mux4ds","children":[]}
,{"id":"dffr_s","children":[]}
,{"id":"mux3ds","children":[]}
,{"id":"sparc_exu_eclccr","children":[{"id":"dff_s","children":[]}
,{"id":"mux2ds","children":[]}
,{"id":"mux3ds","children":[]}
,{"id":"mux4ds","children":[]}
]}
,{"id":"sparc_exu_ecl_wb","children":[{"id":"dff_s","children":[]}
,{"id":"mux4ds","children":[]}
,{"id":"mux2ds","children":[]}
,{"id":"dffr_s","children":[]}
,{"id":"dffe_s","children":[]}
]}
,{"id":"sparc_exu_ecl_eccctl","children":[{"id":"dff_s","children":[]}
,{"id":"mux3ds","children":[]}
]}
,{"id":"sparc_exu_eclbyplog_rs1","children":[{"id":"sparc_exu_eclcomp7","children":[]}
]}
,{"id":"sparc_exu_eclbyplog","children":[{"id":"sparc_exu_eclcomp7","children":[]}
]}
,{"id":"sparc_exu_ecl_divcntl","children":[{"id":"dff_s","children":[]}
,{"id":"sparc_exu_ecl_cnt6","children":[{"id":"dff_s","children":[]}
]}
,{"id":"mux2ds","children":[]}
,{"id":"dp_mux2es","children":[]}
,{"id":"dffe_s","children":[]}
]}
,{"id":"sparc_exu_ecl_mdqctl","children":[{"id":"mux2ds","children":[]}
,{"id":"dffr_s","children":[]}
,{"id":"dff_s","children":[]}
]}
]}
,{"id":"sparc_exu_alu","children":[{"id":"sparc_exu_aluzcmp64","children":[{"id":"sparc_exu_aluor32","children":[]}
]}
,{"id":"dp_mux2es","children":[]}
,{"id":"sparc_exu_aluaddsub","children":[{"id":"dff_s","children":[]}
,{"id":"sparc_exu_aluadder64","children":[]}
,{"id":"sparc_exu_aluspr","children":[]}
]}
,{"id":"dff_s","children":[]}
,{"id":"sparc_exu_alulogic","children":[{"id":"mux4ds","children":[]}
,{"id":"dp_buffer","children":[]}
]}
,{"id":"mux4ds","children":[]}
,{"id":"sparc_exu_alu_16eql","children":[]}
]}
,{"id":"sparc_exu_shft","children":[{"id":"dp_mux2es","children":[]}
,{"id":"mux4ds","children":[]}
,{"id":"dp_buffer","children":[]}
]}
,{"id":"sparc_exu_div","children":[{"id":"dp_buffer","children":[]}
,{"id":"dp_mux2es","children":[]}
,{"id":"sparc_exu_div_32eql","children":[{"id":"sparc_exu_aluor32","children":[]}
]}
,{"id":"sparc_exu_aluor32","children":[]}
,{"id":"mux4ds","children":[]}
,{"id":"mux3ds","children":[]}
,{"id":"dff_s","children":[]}
,{"id":"sparc_exu_aluadder64","children":[]}
,{"id":"sparc_exu_aluspr","children":[]}
,{"id":"sparc_exu_div_yreg","children":[{"id":"mux4ds","children":[]}
,{"id":"dff_s","children":[]}
]}
]}
,{"id":"sparc_exu_rml","children":[{"id":"dffrl_async","children":[]}
,{"id":"dff_s","children":[]}
,{"id":"mux2ds","children":[]}
,{"id":"sparc_exu_rml_inc3","children":[]}
,{"id":"mux3ds","children":[]}
,{"id":"sparc_exu_rml_cwp","children":[{"id":"mux2ds","children":[]}
,{"id":"mux4ds","children":[]}
,{"id":"dff_s","children":[]}
,{"id":"mux3ds","children":[]}
,{"id":"dffr_s","children":[]}
,{"id":"sparc_exu_rndrob","children":[{"id":"dffr_s","children":[]}
]}
]}
,{"id":"sparc_exu_reg","children":[{"id":"mux4ds","children":[]}
,{"id":"mux2ds","children":[]}
,{"id":"dff_s","children":[]}
]}
,{"id":"mux4ds","children":[]}
]}
]}]}